plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':api')
    api 'net.minestom:minestom:2026.01.08-1.21.11'
    api 'org.slf4j:slf4j-api:2.0.9'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    withJavadocJar()
}
