plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    api "org.graalvm.polyglot:polyglot:24.1.0"
    api "org.graalvm.js:js-language:24.1.0"
    api "org.graalvm.truffle:truffle-api:24.1.0"
    api "org.graalvm.sdk:graal-sdk:24.1.0"
    api "org.graalvm.sdk:collections:24.1.0"
    api "org.graalvm.sdk:nativeimage:24.1.0"
    api "org.graalvm.shadowed:icu4j:24.0.0"
    api "com.google.code.gson:gson:2.10.1"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
